writers:
  kafka:
    bootstrap_servers: 127.0.0.1:9092
    topic: test
  file:
    path: ../sport-news.json
  es:
    url: http://localhost:9200 # 支持http basic认证，例如http://elastic:elastic@localhost:9200
    index: sport-news
    id_field: id # 写入es中映射为id的字段，默认为”id“